//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * equalityExpression -> EqualityExpression()
 * nodeOptional -> [ AndOperand() ]
 * </PRE>
 */
public class AndExpression implements Node {
   public EqualityExpression equalityExpression;
   public NodeOptional nodeOptional;

   public AndExpression(EqualityExpression n0, NodeOptional n1) {
      equalityExpression = n0;
      nodeOptional = n1;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

