//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> &lt;AND&gt;
 * andExpression -> AndExpression()
 * </PRE>
 */
public class AndOperand implements Node {
   public NodeToken nodeToken;
   public AndExpression andExpression;

   public AndOperand(NodeToken n0, AndExpression n1) {
      nodeToken = n0;
      andExpression = n1;
   }

   public AndOperand(AndExpression n0) {
      nodeToken = new NodeToken("&");
      andExpression = n0;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

