//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> &lt;BIT&gt;
 * nodeChoice -> ( ":" &lt;INTEGER_LITERAL&gt; | &lt;LT&gt; ShiftExpression() &lt;GT&gt; )
 * </PRE>
 */
public class BitField implements Node {
   public NodeToken nodeToken;
   public NodeChoice nodeChoice;

   public BitField(NodeToken n0, NodeChoice n1) {
      nodeToken = n0;
      nodeChoice = n1;
   }

   public BitField(NodeChoice n0) {
      nodeToken = new NodeToken("bit");
      nodeChoice = n0;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

