//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeOptional -> [ ByteOrderModifier() ]
 * nodeChoice -> ( &lt;UINT8&gt; | &lt;UINT16&gt; | &lt;UINT32&gt; | &lt;UINT64&gt; | &lt;INT8&gt; | &lt;INT16&gt; | &lt;INT32&gt; | &lt;INT64&gt; | &lt;STRING&gt; | BitField() )
 * </PRE>
 */
public class BuiltinType implements Node {
   public NodeOptional nodeOptional;
   public NodeChoice nodeChoice;

   public BuiltinType(NodeOptional n0, NodeChoice n1) {
      nodeOptional = n0;
      nodeChoice = n1;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

