//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> "("
 * definedType -> DefinedType()
 * nodeToken1 -> ")"
 * castExpression -> CastExpression()
 * </PRE>
 */
public class CastOperand implements Node {
   public NodeToken nodeToken;
   public DefinedType definedType;
   public NodeToken nodeToken1;
   public CastExpression castExpression;

   public CastOperand(NodeToken n0, DefinedType n1, NodeToken n2, CastExpression n3) {
      nodeToken = n0;
      definedType = n1;
      nodeToken1 = n2;
      castExpression = n3;
   }

   public CastOperand(DefinedType n0, CastExpression n1) {
      nodeToken = new NodeToken("(");
      definedType = n0;
      nodeToken1 = new NodeToken(")");
      castExpression = n1;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

