//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> ","
 * assignmentExpression -> AssignmentExpression()
 * </PRE>
 */
public class CommaOperand implements Node {
   public NodeToken nodeToken;
   public AssignmentExpression assignmentExpression;

   public CommaOperand(NodeToken n0, AssignmentExpression n1) {
      nodeToken = n0;
      assignmentExpression = n1;
   }

   public CommaOperand(AssignmentExpression n0) {
      nodeToken = new NodeToken(",");
      assignmentExpression = n0;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

