//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * logicalOrExpression -> LogicalOrExpression()
 * nodeOptional -> [ ConditionalExpressionOperand() ]
 * </PRE>
 */
public class ConditionalExpression implements Node {
   public LogicalOrExpression logicalOrExpression;
   public NodeOptional nodeOptional;

   public ConditionalExpression(LogicalOrExpression n0, NodeOptional n1) {
      logicalOrExpression = n0;
      nodeOptional = n1;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

