//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> &lt;QUESTIONMARK&gt;
 * expression -> Expression()
 * nodeToken1 -> ":"
 * conditionalExpression -> ConditionalExpression()
 * </PRE>
 */
public class ConditionalExpressionOperand implements Node {
   public NodeToken nodeToken;
   public Expression expression;
   public NodeToken nodeToken1;
   public ConditionalExpression conditionalExpression;

   public ConditionalExpressionOperand(NodeToken n0, Expression n1, NodeToken n2, ConditionalExpression n3) {
      nodeToken = n0;
      expression = n1;
      nodeToken1 = n2;
      conditionalExpression = n3;
   }

   public ConditionalExpressionOperand(Expression n0, ConditionalExpression n1) {
      nodeToken = new NodeToken("?");
      expression = n0;
      nodeToken1 = new NodeToken(":");
      conditionalExpression = n1;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

