//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * expression -> Expression()
 * </PRE>
 */
public class ConditionExpression implements Node {
   public Expression expression;

   public ConditionExpression(Expression n0) {
      expression = n0;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

