//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> &lt;CONST&gt;
 * typeDeclaration -> TypeDeclaration()
 * nodeToken1 -> &lt;IDENTIFIER&gt;
 * nodeToken2 -> "="
 * typeValue -> TypeValue()
 * </PRE>
 */
public class ConstDeclaration implements Node {
   public NodeToken nodeToken;
   public TypeDeclaration typeDeclaration;
   public NodeToken nodeToken1;
   public NodeToken nodeToken2;
   public TypeValue typeValue;

   public ConstDeclaration(NodeToken n0, TypeDeclaration n1, NodeToken n2, NodeToken n3, TypeValue n4) {
      nodeToken = n0;
      typeDeclaration = n1;
      nodeToken1 = n2;
      nodeToken2 = n3;
      typeValue = n4;
   }

   public ConstDeclaration(TypeDeclaration n0, NodeToken n1, TypeValue n2) {
      nodeToken = new NodeToken("const");
      typeDeclaration = n0;
      nodeToken1 = n1;
      nodeToken2 = new NodeToken("=");
      typeValue = n2;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

