//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * conditionalExpression -> ConditionalExpression()
 * </PRE>
 */
public class ConstantExpression implements Node {
   public ConditionalExpression conditionalExpression;

   public ConstantExpression(ConditionalExpression n0) {
      conditionalExpression = n0;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

