//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeChoice -> FieldDefinition() ";"
 *       | ConditionDefinition()
 *       | ConstDeclaration() ";"
 *       | SqlFieldDefinition() ";"
 * </PRE>
 */
public class Declaration implements Node {
   public NodeChoice nodeChoice;

   public Declaration(NodeChoice n0) {
      nodeChoice = n0;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

