//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> "."
 * nodeToken1 -> &lt;IDENTIFIER&gt;
 * </PRE>
 */
public class DotOperand implements Node {
   public NodeToken nodeToken;
   public NodeToken nodeToken1;

   public DotOperand(NodeToken n0, NodeToken n1) {
      nodeToken = n0;
      nodeToken1 = n1;
   }

   public DotOperand(NodeToken n0) {
      nodeToken = new NodeToken(".");
      nodeToken1 = n0;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

