//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * relationalExpression -> RelationalExpression()
 * nodeOptional -> [ EqualityOperand() ]
 * </PRE>
 */
public class EqualityExpression implements Node {
   public RelationalExpression relationalExpression;
   public NodeOptional nodeOptional;

   public EqualityExpression(RelationalExpression n0, NodeOptional n1) {
      relationalExpression = n0;
      nodeOptional = n1;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

