//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeChoice -> ( &lt;EQ&gt; | &lt;NE&gt; )
 * equalityExpression -> EqualityExpression()
 * </PRE>
 */
public class EqualityOperand implements Node {
   public NodeChoice nodeChoice;
   public EqualityExpression equalityExpression;

   public EqualityOperand(NodeChoice n0, EqualityExpression n1) {
      nodeChoice = n0;
      equalityExpression = n1;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

