//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> &lt;XOR&gt;
 * exclusiveOrExpression -> ExclusiveOrExpression()
 * </PRE>
 */
public class ExclusiveOrOperand implements Node {
   public NodeToken nodeToken;
   public ExclusiveOrExpression exclusiveOrExpression;

   public ExclusiveOrOperand(NodeToken n0, ExclusiveOrExpression n1) {
      nodeToken = n0;
      exclusiveOrExpression = n1;
   }

   public ExclusiveOrOperand(ExclusiveOrExpression n0) {
      nodeToken = new NodeToken("^");
      exclusiveOrExpression = n0;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

