//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * andExpression -> AndExpression()
 * nodeOptional -> [ ExclusiveOrOperand() ]
 * </PRE>
 */
public class ExclusiveOrExpression implements Node {
   public AndExpression andExpression;
   public NodeOptional nodeOptional;

   public ExclusiveOrExpression(AndExpression n0, NodeOptional n1) {
      andExpression = n0;
      nodeOptional = n1;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

