//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * assignmentExpression -> AssignmentExpression()
 * nodeListOptional -> ( CommaOperand() )*
 * </PRE>
 */
public class Expression implements Node {
   public AssignmentExpression assignmentExpression;
   public NodeListOptional nodeListOptional;

   public Expression(AssignmentExpression n0, NodeListOptional n1) {
      assignmentExpression = n0;
      nodeListOptional = n1;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

