//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> "="
 * typeValue -> TypeValue()
 * </PRE>
 */
public class FieldInitializer implements Node {
   public NodeToken nodeToken;
   public TypeValue typeValue;

   public FieldInitializer(NodeToken n0, TypeValue n1) {
      nodeToken = n0;
      typeValue = n1;
   }

   public FieldInitializer(TypeValue n0) {
      nodeToken = new NodeToken("=");
      typeValue = n0;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

