//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> &lt;IF&gt;
 * expression -> Expression()
 * </PRE>
 */
public class FieldOptionalClause implements Node {
   public NodeToken nodeToken;
   public Expression expression;

   public FieldOptionalClause(NodeToken n0, Expression n1) {
      nodeToken = n0;
      expression = n1;
   }

   public FieldOptionalClause(Expression n0) {
      nodeToken = new NodeToken("if");
      expression = n0;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

