//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * expression -> Expression()
 * nodeToken -> "::"
 * </PRE>
 */
public class GlobalLabel implements Node {
   public Expression expression;
   public NodeToken nodeToken;

   public GlobalLabel(Expression n0, NodeToken n1) {
      expression = n0;
      nodeToken = n1;
   }

   public GlobalLabel(Expression n0) {
      expression = n0;
      nodeToken = new NodeToken("::");
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

