//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> &lt;OR&gt;
 * inclusiveOrExpression -> InclusiveOrExpression()
 * </PRE>
 */
public class InclusiveOrOperand implements Node {
   public NodeToken nodeToken;
   public InclusiveOrExpression inclusiveOrExpression;

   public InclusiveOrOperand(NodeToken n0, InclusiveOrExpression n1) {
      nodeToken = n0;
      inclusiveOrExpression = n1;
   }

   public InclusiveOrOperand(InclusiveOrExpression n0) {
      nodeToken = new NodeToken("|");
      inclusiveOrExpression = n0;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

