//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeOptional -> [ GlobalLabel() ]
 * expression -> Expression()
 * nodeToken -> ":"
 * </PRE>
 */
public class Label implements Node {
   public NodeOptional nodeOptional;
   public Expression expression;
   public NodeToken nodeToken;

   public Label(NodeOptional n0, Expression n1, NodeToken n2) {
      nodeOptional = n0;
      expression = n1;
      nodeToken = n2;
   }

   public Label(NodeOptional n0, Expression n1) {
      nodeOptional = n0;
      expression = n1;
      nodeToken = new NodeToken(":");
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

