//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * inclusiveOrExpression -> InclusiveOrExpression()
 * nodeOptional -> [ LogicalAndOperand() ]
 * </PRE>
 */
public class LogicalAndExpression implements Node {
   public InclusiveOrExpression inclusiveOrExpression;
   public NodeOptional nodeOptional;

   public LogicalAndExpression(InclusiveOrExpression n0, NodeOptional n1) {
      inclusiveOrExpression = n0;
      nodeOptional = n1;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

