//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> &lt;LOGICALOR&gt;
 * logicalOrExpression -> LogicalOrExpression()
 * </PRE>
 */
public class LogicalOrOperand implements Node {
   public NodeToken nodeToken;
   public LogicalOrExpression logicalOrExpression;

   public LogicalOrOperand(NodeToken n0, LogicalOrExpression n1) {
      nodeToken = n0;
      logicalOrExpression = n1;
   }

   public LogicalOrOperand(LogicalOrExpression n0) {
      nodeToken = new NodeToken("||");
      logicalOrExpression = n0;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

