//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> &lt;LOGICALAND&gt;
 * logicalAndExpression -> LogicalAndExpression()
 * </PRE>
 */
public class LogicalAndOperand implements Node {
   public NodeToken nodeToken;
   public LogicalAndExpression logicalAndExpression;

   public LogicalAndOperand(NodeToken n0, LogicalAndExpression n1) {
      nodeToken = n0;
      logicalAndExpression = n1;
   }

   public LogicalAndOperand(LogicalAndExpression n0) {
      nodeToken = new NodeToken("&&");
      logicalAndExpression = n0;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

