//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * logicalAndExpression -> LogicalAndExpression()
 * nodeOptional -> [ LogicalOrOperand() ]
 * </PRE>
 */
public class LogicalOrExpression implements Node {
   public LogicalAndExpression logicalAndExpression;
   public NodeOptional nodeOptional;

   public LogicalOrExpression(LogicalAndExpression n0, NodeOptional n1) {
      logicalAndExpression = n0;
      nodeOptional = n1;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

