//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * castExpression -> CastExpression()
 * nodeListOptional -> ( Multiplicand() )*
 * </PRE>
 */
public class MultiplicativeExpression implements Node {
   public CastExpression castExpression;
   public NodeListOptional nodeListOptional;

   public MultiplicativeExpression(CastExpression n0, NodeListOptional n1) {
      castExpression = n0;
      nodeListOptional = n1;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

