//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * The interface which all syntax tree classes must implement.
 */
public interface Node extends java.io.Serializable {
   public void accept(datascript.visitor.Visitor v);
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu);

}

