//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * expression -> Expression()
 * nodeOptional -> [ UpperBoundExpression() ]
 * </PRE>
 */
public class RangeExpression implements Node {
   public Expression expression;
   public NodeOptional nodeOptional;

   public RangeExpression(Expression n0, NodeOptional n1) {
      expression = n0;
      nodeOptional = n1;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

