//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * shiftExpression -> ShiftExpression()
 * nodeListOptional -> ( RelationalOperand() )*
 * </PRE>
 */
public class RelationalExpression implements Node {
   public ShiftExpression shiftExpression;
   public NodeListOptional nodeListOptional;

   public RelationalExpression(ShiftExpression n0, NodeListOptional n1) {
      shiftExpression = n0;
      nodeListOptional = n1;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

