//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeChoice -> ( &lt;LT&gt; | &lt;LE&gt; | &lt;GT&gt; | &lt;GE&gt; )
 * shiftExpression -> ShiftExpression()
 * </PRE>
 */
public class RelationalOperand implements Node {
   public NodeChoice nodeChoice;
   public ShiftExpression shiftExpression;

   public RelationalOperand(NodeChoice n0, ShiftExpression n1) {
      nodeChoice = n0;
      shiftExpression = n1;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

