//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * additiveExpression -> AdditiveExpression()
 * nodeListOptional -> ( ShiftOperand() )*
 * </PRE>
 */
public class ShiftExpression implements Node {
   public AdditiveExpression additiveExpression;
   public NodeListOptional nodeListOptional;

   public ShiftExpression(AdditiveExpression n0, NodeListOptional n1) {
      additiveExpression = n0;
      nodeListOptional = n1;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

