//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeChoice -> ( &lt;SHIFTLEFT&gt; | &lt;SHIFTRIGHT&gt; )
 * additiveExpression -> AdditiveExpression()
 * </PRE>
 */
public class ShiftOperand implements Node {
   public NodeChoice nodeChoice;
   public AdditiveExpression additiveExpression;

   public ShiftOperand(NodeChoice n0, AdditiveExpression n1) {
      nodeChoice = n0;
      additiveExpression = n1;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

