//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> &lt;SIZEOF&gt;
 * unaryExpression -> UnaryExpression()
 * </PRE>
 */
public class SizeOfOperand implements Node {
   public NodeToken nodeToken;
   public UnaryExpression unaryExpression;

   public SizeOfOperand(NodeToken n0, UnaryExpression n1) {
      nodeToken = n0;
      unaryExpression = n1;
   }

   public SizeOfOperand(UnaryExpression n0) {
      nodeToken = new NodeToken("sizeof");
      unaryExpression = n0;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

