//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> &lt;SQL&gt;
 * sqlSyntax -> SqlSyntax()
 * nodeListOptional -> ( "," SqlSyntax() )*
 * </PRE>
 */
public class SqlCondition implements Node {
   public NodeToken nodeToken;
   public SqlSyntax sqlSyntax;
   public NodeListOptional nodeListOptional;

   public SqlCondition(NodeToken n0, SqlSyntax n1, NodeListOptional n2) {
      nodeToken = n0;
      sqlSyntax = n1;
      nodeListOptional = n2;
   }

   public SqlCondition(SqlSyntax n0, NodeListOptional n1) {
      nodeToken = new NodeToken("sql");
      sqlSyntax = n0;
      nodeListOptional = n1;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

