//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * sqlType -> SqlType()
 * nodeOptional -> [ &lt;IDENTIFIER&gt; ]
 * nodeSequence -> ( SqlFieldContent() )
 * nodeListOptional -> ( &lt;STRING&gt; )*
 * </PRE>
 */
public class SqlFieldDefinition implements Node {
   public SqlType sqlType;
   public NodeOptional nodeOptional;
   public NodeSequence nodeSequence;
   public NodeListOptional nodeListOptional;

   public SqlFieldDefinition(SqlType n0, NodeOptional n1, NodeSequence n2, NodeListOptional n3) {
      sqlType = n0;
      nodeOptional = n1;
      nodeSequence = n2;
      nodeListOptional = n3;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

