//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * sqlSyntax -> SqlSyntax()
 * nodeListOptional -> ( "," SqlSyntax() )*
 * </PRE>
 */
public class SqlFieldContent implements Node {
   public SqlSyntax sqlSyntax;
   public NodeListOptional nodeListOptional;

   public SqlFieldContent(SqlSyntax n0, NodeListOptional n1) {
      sqlSyntax = n0;
      nodeListOptional = n1;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

