//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeChoice -> &lt;INDEX&gt;
 *       | &lt;CONSTRAINT&gt;
 * </PRE>
 */
public class SqlType implements Node {
   public NodeChoice nodeChoice;

   public SqlType(NodeChoice n0) {
      nodeChoice = n0;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

