//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeChoice -> ( &lt;PLUS&gt; | &lt;MINUS&gt; )
 * multiplicativeExpression -> MultiplicativeExpression()
 * </PRE>
 */
public class Summand implements Node {
   public NodeChoice nodeChoice;
   public MultiplicativeExpression multiplicativeExpression;

   public Summand(NodeChoice n0, MultiplicativeExpression n1) {
      nodeChoice = n0;
      multiplicativeExpression = n1;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

