//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * declarationList -> DeclarationList()
 * </PRE>
 */
public class TranslationUnit implements Node {
   public DeclarationList declarationList;

   public TranslationUnit(DeclarationList n0) {
      declarationList = n0;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

