//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> &lt;IDENTIFIER&gt;
 * nodeListOptional -> ( DotOperand() )*
 * </PRE>
 */
public class TypeSymbol implements Node {
   public NodeToken nodeToken;
   public NodeListOptional nodeListOptional;

   public TypeSymbol(NodeToken n0, NodeListOptional n1) {
      nodeToken = n0;
      nodeListOptional = n1;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

