//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * typeValue -> TypeValue()
 * nodeListOptional -> ( "," TypeValue() )*
 * </PRE>
 */
public class TypeValueList implements Node {
   public TypeValue typeValue;
   public NodeListOptional nodeListOptional;

   public TypeValueList(TypeValue n0, NodeListOptional n1) {
      typeValue = n0;
      nodeListOptional = n1;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

