//
// Generated by JTB 1.2.2
//

package datascript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeChoice -> ( &lt;PLUS&gt; | &lt;MINUS&gt; | &lt;TILDE&gt; | &lt;BANG&gt; )
 * castExpression -> CastExpression()
 * </PRE>
 */
public class UnaryOperand implements Node {
   public NodeChoice nodeChoice;
   public CastExpression castExpression;

   public UnaryOperand(NodeChoice n0, CastExpression n1) {
      nodeChoice = n0;
      castExpression = n1;
   }

   public void accept(datascript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(datascript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

