//
// Generated by JTB 1.2.2
//

package datascript.visitor;
import datascript.syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class DepthFirstVisitor implements Visitor {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public void visit(NodeList n) {
      for ( Enumeration e = n.elements(); e.hasMoreElements(); )
         ((Node)e.nextElement()).accept(this);
   }

   public void visit(NodeListOptional n) {
      if ( n.present() )
         for ( Enumeration e = n.elements(); e.hasMoreElements(); )
            ((Node)e.nextElement()).accept(this);
   }

   public void visit(NodeOptional n) {
      if ( n.present() )
         n.node.accept(this);
   }

   public void visit(NodeSequence n) {
      for ( Enumeration e = n.elements(); e.hasMoreElements(); )
         ((Node)e.nextElement()).accept(this);
   }

   public void visit(NodeToken n) { }

   //
   // User-generated visitor methods below
   //

   /**
    * <PRE>
    * declarationList -> DeclarationList()
    * </PRE>
    */
   public void visit(TranslationUnit n) {
      n.declarationList.accept(this);
   }

   /**
    * <PRE>
    * nodeListOptional -> ( Declaration() )*
    * </PRE>
    */
   public void visit(DeclarationList n) {
      n.nodeListOptional.accept(this);
   }

   /**
    * <PRE>
    * nodeChoice -> FieldDefinition() ";"
    *       | ConditionDefinition()
    *       | ConstDeclaration() ";"
    *       | SqlFieldDefinition() ";"
    * </PRE>
    */
   public void visit(Declaration n) {
      n.nodeChoice.accept(this);
   }

   /**
    * <PRE>
    * nodeOptional -> [ GlobalLabel() ]
    * expression -> Expression()
    * nodeToken -> ":"
    * </PRE>
    */
   public void visit(Label n) {
      n.nodeOptional.accept(this);
      n.expression.accept(this);
      n.nodeToken.accept(this);
   }

   /**
    * <PRE>
    * expression -> Expression()
    * nodeToken -> "::"
    * </PRE>
    */
   public void visit(GlobalLabel n) {
      n.expression.accept(this);
      n.nodeToken.accept(this);
   }

   /**
    * <PRE>
    * nodeToken -> &lt;CONDITION&gt;
    * nodeToken1 -> &lt;IDENTIFIER&gt;
    * nodeToken2 -> "("
    * nodeOptional -> [ ParameterDefinition() ( "," ParameterDefinition() )* ]
    * nodeToken3 -> ")"
    * nodeToken4 -> "{"
    * nodeListOptional -> ( ConditionExpression() ";" )*
    * nodeToken5 -> "}"
    * </PRE>
    */
   public void visit(ConditionDefinition n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.nodeOptional.accept(this);
      n.nodeToken3.accept(this);
      n.nodeToken4.accept(this);
      n.nodeListOptional.accept(this);
      n.nodeToken5.accept(this);
   }

   /**
    * <PRE>
    * typeDeclaration -> TypeDeclaration()
    * nodeToken -> &lt;IDENTIFIER&gt;
    * </PRE>
    */
   public void visit(ParameterDefinition n) {
      n.typeDeclaration.accept(this);
      n.nodeToken.accept(this);
   }

   /**
    * <PRE>
    * expression -> Expression()
    * </PRE>
    */
   public void visit(ConditionExpression n) {
      n.expression.accept(this);
   }

   /**
    * <PRE>
    * nodeChoice -> ( &lt;ENUM&gt; | &lt;BITMASK&gt; )
    * builtinType -> BuiltinType()
    * nodeOptional -> [ &lt;IDENTIFIER&gt; ]
    * nodeToken -> "{"
    * enumItem -> EnumItem()
    * nodeListOptional -> ( "," EnumItem() )*
    * nodeToken1 -> "}"
    * </PRE>
    */
   public void visit(EnumDeclaration n) {
      n.nodeChoice.accept(this);
      n.builtinType.accept(this);
      n.nodeOptional.accept(this);
      n.nodeToken.accept(this);
      n.enumItem.accept(this);
      n.nodeListOptional.accept(this);
      n.nodeToken1.accept(this);
   }

   /**
    * <PRE>
    * nodeToken -> &lt;IDENTIFIER&gt;
    * nodeOptional -> [ "=" ConstantExpression() ]
    * </PRE>
    */
   public void visit(EnumItem n) {
      n.nodeToken.accept(this);
      n.nodeOptional.accept(this);
   }

   /**
    * <PRE>
    * nodeToken -> &lt;CONST&gt;
    * typeDeclaration -> TypeDeclaration()
    * nodeToken1 -> &lt;IDENTIFIER&gt;
    * nodeToken2 -> "="
    * typeValue -> TypeValue()
    * </PRE>
    */
   public void visit(ConstDeclaration n) {
      n.nodeToken.accept(this);
      n.typeDeclaration.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.typeValue.accept(this);
   }

   /**
    * <PRE>
    * nodeChoice -> ConstantExpression()
    *       | "{" TypeValueList() "}"
    * </PRE>
    */
   public void visit(TypeValue n) {
      n.nodeChoice.accept(this);
   }

   /**
    * <PRE>
    * typeValue -> TypeValue()
    * nodeListOptional -> ( "," TypeValue() )*
    * </PRE>
    */
   public void visit(TypeValueList n) {
      n.typeValue.accept(this);
      n.nodeListOptional.accept(this);
   }

   /**
    * <PRE>
    * sqlType -> SqlType()
    * nodeOptional -> [ &lt;IDENTIFIER&gt; ]
    * nodeSequence -> ( SqlFieldContent() )
    * nodeListOptional -> ( &lt;STRING&gt; )*
    * </PRE>
    */
   public void visit(SqlFieldDefinition n) {
      n.sqlType.accept(this);
      n.nodeOptional.accept(this);
      n.nodeSequence.accept(this);
      n.nodeListOptional.accept(this);
   }

   /**
    * <PRE>
    * sqlSyntax -> SqlSyntax()
    * nodeListOptional -> ( "," SqlSyntax() )*
    * </PRE>
    */
   public void visit(SqlFieldContent n) {
      n.sqlSyntax.accept(this);
      n.nodeListOptional.accept(this);
   }

   /**
    * <PRE>
    * nodeChoice -> &lt;INDEX&gt;
    *       | &lt;CONSTRAINT&gt;
    * </PRE>
    */
   public void visit(SqlType n) {
      n.nodeChoice.accept(this);
   }

   /**
    * <PRE>
    * nodeOptional -> [ Label() ]
    * typeDeclaration -> TypeDeclaration()
    * nodeOptional1 -> [ TypeArgumentList() ]
    * nodeOptional2 -> [ &lt;IDENTIFIER&gt; ]
    * nodeListOptional -> ( ArrayRange() )*
    * nodeOptional3 -> [ FieldInitializer() ]
    * nodeOptional4 -> [ FieldCondition() ]
    * nodeOptional5 -> [ SqlCondition() ]
    * nodeOptional6 -> [ FieldOptionalClause() ]
    * nodeListOptional1 -> ( &lt;STRING&gt; )*
    * </PRE>
    */
   public void visit(FieldDefinition n) {
      n.nodeOptional.accept(this);
      n.typeDeclaration.accept(this);
      n.nodeOptional1.accept(this);
      n.nodeOptional2.accept(this);
      n.nodeListOptional.accept(this);
      n.nodeOptional3.accept(this);
      n.nodeOptional4.accept(this);
      n.nodeOptional5.accept(this);
      n.nodeOptional6.accept(this);
      n.nodeListOptional1.accept(this);
   }

   /**
    * <PRE>
    * nodeToken -> "("
    * nodeOptional -> [ FunctionArgument() ( "," FunctionArgument() )* ]
    * nodeToken1 -> ")"
    * </PRE>
    */
   public void visit(TypeArgumentList n) {
      n.nodeToken.accept(this);
      n.nodeOptional.accept(this);
      n.nodeToken1.accept(this);
   }

   /**
    * <PRE>
    * nodeToken -> "="
    * typeValue -> TypeValue()
    * </PRE>
    */
   public void visit(FieldInitializer n) {
      n.nodeToken.accept(this);
      n.typeValue.accept(this);
   }

   /**
    * <PRE>
    * nodeToken -> &lt;IF&gt;
    * expression -> Expression()
    * </PRE>
    */
   public void visit(FieldOptionalClause n) {
      n.nodeToken.accept(this);
      n.expression.accept(this);
   }

   /**
    * <PRE>
    * nodeToken -> ":"
    * expression -> Expression()
    * </PRE>
    */
   public void visit(FieldCondition n) {
      n.nodeToken.accept(this);
      n.expression.accept(this);
   }

   /**
    * <PRE>
    * nodeToken -> &lt;SQL&gt;
    * sqlSyntax -> SqlSyntax()
    * nodeListOptional -> ( "," SqlSyntax() )*
    * </PRE>
    */
   public void visit(SqlCondition n) {
      n.nodeToken.accept(this);
      n.sqlSyntax.accept(this);
      n.nodeListOptional.accept(this);
   }

   /**
    * <PRE>
    * nodeToken -> &lt;STRING_LITERAL&gt;
    * </PRE>
    */
   public void visit(SqlSyntax n) {
      n.nodeToken.accept(this);
   }

   /**
    * <PRE>
    * nodeChoice -> StructDeclaration()
    *       | DefinedType()
    *       | EnumDeclaration()
    * </PRE>
    */
   public void visit(TypeDeclaration n) {
      n.nodeChoice.accept(this);
   }

   /**
    * <PRE>
    * nodeOptional -> [ ByteOrderModifier() ]
    * nodeOptional1 -> [ &lt;UNION&gt; | &lt;DATABASE&gt; | &lt;TABLE&gt; | &lt;SQLINTEGER&gt; | &lt;SQLTEXT&gt; ]
    * nodeOptional2 -> [ &lt;IDENTIFIER&gt; ]
    * nodeOptional3 -> [ "(" ParameterDefinition() ( "," ParameterDefinition() )* ")" ]
    * nodeToken -> "{"
    * declarationList -> DeclarationList()
    * nodeToken1 -> "}"
    * </PRE>
    */
   public void visit(StructDeclaration n) {
      n.nodeOptional.accept(this);
      n.nodeOptional1.accept(this);
      n.nodeOptional2.accept(this);
      n.nodeOptional3.accept(this);
      n.nodeToken.accept(this);
      n.declarationList.accept(this);
      n.nodeToken1.accept(this);
   }

   /**
    * <PRE>
    * nodeChoice -> TypeSymbol()
    *       | BuiltinType()
    * </PRE>
    */
   public void visit(DefinedType n) {
      n.nodeChoice.accept(this);
   }

   /**
    * <PRE>
    * nodeToken -> &lt;IDENTIFIER&gt;
    * nodeListOptional -> ( DotOperand() )*
    * </PRE>
    */
   public void visit(TypeSymbol n) {
      n.nodeToken.accept(this);
      n.nodeListOptional.accept(this);
   }

   /**
    * <PRE>
    * nodeOptional -> [ ByteOrderModifier() ]
    * nodeChoice -> ( &lt;UINT8&gt; | &lt;UINT16&gt; | &lt;UINT32&gt; | &lt;UINT64&gt; | &lt;INT8&gt; | &lt;INT16&gt; | &lt;INT32&gt; | &lt;INT64&gt; | &lt;STRING&gt; | BitField() )
    * </PRE>
    */
   public void visit(BuiltinType n) {
      n.nodeOptional.accept(this);
      n.nodeChoice.accept(this);
   }

   /**
    * <PRE>
    * nodeToken -> &lt;BIT&gt;
    * nodeChoice -> ( ":" &lt;INTEGER_LITERAL&gt; | &lt;LT&gt; ShiftExpression() &lt;GT&gt; )
    * </PRE>
    */
   public void visit(BitField n) {
      n.nodeToken.accept(this);
      n.nodeChoice.accept(this);
   }

   /**
    * <PRE>
    * nodeChoice -> &lt;BIG&gt;
    *       | &lt;LITTLE&gt;
    * </PRE>
    */
   public void visit(ByteOrderModifier n) {
      n.nodeChoice.accept(this);
   }

   /**
    * <PRE>
    * nodeToken -> "["
    * nodeOptional -> [ RangeExpression() ]
    * nodeToken1 -> "]"
    * </PRE>
    */
   public void visit(ArrayRange n) {
      n.nodeToken.accept(this);
      n.nodeOptional.accept(this);
      n.nodeToken1.accept(this);
   }

   /**
    * <PRE>
    * assignmentExpression -> AssignmentExpression()
    * nodeListOptional -> ( CommaOperand() )*
    * </PRE>
    */
   public void visit(Expression n) {
      n.assignmentExpression.accept(this);
      n.nodeListOptional.accept(this);
   }

   /**
    * <PRE>
    * nodeToken -> ","
    * assignmentExpression -> AssignmentExpression()
    * </PRE>
    */
   public void visit(CommaOperand n) {
      n.nodeToken.accept(this);
      n.assignmentExpression.accept(this);
   }

   /**
    * <PRE>
    * nodeChoice -> UnaryExpression() AssignmentOperator() AssignmentExpression()
    *       | QuantifiedExpression()
    * </PRE>
    */
   public void visit(AssignmentExpression n) {
      n.nodeChoice.accept(this);
   }

   /**
    * <PRE>
    * nodeChoice -> ( "=" | "*=" | "/=" | "%=" | "+=" | "-=" | "&lt;&lt;=" | "&gt;&gt;=" | "&=" | "^=" | "|=" )
    * </PRE>
    */
   public void visit(AssignmentOperator n) {
      n.nodeChoice.accept(this);
   }

   /**
    * <PRE>
    * nodeOptional -> [ Quantifier() ]
    * conditionalExpression -> ConditionalExpression()
    * </PRE>
    */
   public void visit(QuantifiedExpression n) {
      n.nodeOptional.accept(this);
      n.conditionalExpression.accept(this);
   }

   /**
    * <PRE>
    * nodeToken -> &lt;FORALL&gt;
    * nodeToken1 -> &lt;IDENTIFIER&gt;
    * nodeToken2 -> &lt;IN&gt;
    * unaryExpression -> UnaryExpression()
    * nodeToken3 -> ":"
    * </PRE>
    */
   public void visit(Quantifier n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
      n.nodeToken2.accept(this);
      n.unaryExpression.accept(this);
      n.nodeToken3.accept(this);
   }

   /**
    * <PRE>
    * logicalOrExpression -> LogicalOrExpression()
    * nodeOptional -> [ ConditionalExpressionOperand() ]
    * </PRE>
    */
   public void visit(ConditionalExpression n) {
      n.logicalOrExpression.accept(this);
      n.nodeOptional.accept(this);
   }

   /**
    * <PRE>
    * nodeToken -> &lt;QUESTIONMARK&gt;
    * expression -> Expression()
    * nodeToken1 -> ":"
    * conditionalExpression -> ConditionalExpression()
    * </PRE>
    */
   public void visit(ConditionalExpressionOperand n) {
      n.nodeToken.accept(this);
      n.expression.accept(this);
      n.nodeToken1.accept(this);
      n.conditionalExpression.accept(this);
   }

   /**
    * <PRE>
    * conditionalExpression -> ConditionalExpression()
    * </PRE>
    */
   public void visit(ConstantExpression n) {
      n.conditionalExpression.accept(this);
   }

   /**
    * <PRE>
    * expression -> Expression()
    * nodeOptional -> [ UpperBoundExpression() ]
    * </PRE>
    */
   public void visit(RangeExpression n) {
      n.expression.accept(this);
      n.nodeOptional.accept(this);
   }

   /**
    * <PRE>
    * nodeToken -> &lt;RANGE&gt;
    * expression -> Expression()
    * </PRE>
    */
   public void visit(UpperBoundExpression n) {
      n.nodeToken.accept(this);
      n.expression.accept(this);
   }

   /**
    * <PRE>
    * logicalAndExpression -> LogicalAndExpression()
    * nodeOptional -> [ LogicalOrOperand() ]
    * </PRE>
    */
   public void visit(LogicalOrExpression n) {
      n.logicalAndExpression.accept(this);
      n.nodeOptional.accept(this);
   }

   /**
    * <PRE>
    * nodeToken -> &lt;LOGICALOR&gt;
    * logicalOrExpression -> LogicalOrExpression()
    * </PRE>
    */
   public void visit(LogicalOrOperand n) {
      n.nodeToken.accept(this);
      n.logicalOrExpression.accept(this);
   }

   /**
    * <PRE>
    * inclusiveOrExpression -> InclusiveOrExpression()
    * nodeOptional -> [ LogicalAndOperand() ]
    * </PRE>
    */
   public void visit(LogicalAndExpression n) {
      n.inclusiveOrExpression.accept(this);
      n.nodeOptional.accept(this);
   }

   /**
    * <PRE>
    * nodeToken -> &lt;LOGICALAND&gt;
    * logicalAndExpression -> LogicalAndExpression()
    * </PRE>
    */
   public void visit(LogicalAndOperand n) {
      n.nodeToken.accept(this);
      n.logicalAndExpression.accept(this);
   }

   /**
    * <PRE>
    * exclusiveOrExpression -> ExclusiveOrExpression()
    * nodeOptional -> [ InclusiveOrOperand() ]
    * </PRE>
    */
   public void visit(InclusiveOrExpression n) {
      n.exclusiveOrExpression.accept(this);
      n.nodeOptional.accept(this);
   }

   /**
    * <PRE>
    * nodeToken -> &lt;OR&gt;
    * inclusiveOrExpression -> InclusiveOrExpression()
    * </PRE>
    */
   public void visit(InclusiveOrOperand n) {
      n.nodeToken.accept(this);
      n.inclusiveOrExpression.accept(this);
   }

   /**
    * <PRE>
    * andExpression -> AndExpression()
    * nodeOptional -> [ ExclusiveOrOperand() ]
    * </PRE>
    */
   public void visit(ExclusiveOrExpression n) {
      n.andExpression.accept(this);
      n.nodeOptional.accept(this);
   }

   /**
    * <PRE>
    * nodeToken -> &lt;XOR&gt;
    * exclusiveOrExpression -> ExclusiveOrExpression()
    * </PRE>
    */
   public void visit(ExclusiveOrOperand n) {
      n.nodeToken.accept(this);
      n.exclusiveOrExpression.accept(this);
   }

   /**
    * <PRE>
    * equalityExpression -> EqualityExpression()
    * nodeOptional -> [ AndOperand() ]
    * </PRE>
    */
   public void visit(AndExpression n) {
      n.equalityExpression.accept(this);
      n.nodeOptional.accept(this);
   }

   /**
    * <PRE>
    * nodeToken -> &lt;AND&gt;
    * andExpression -> AndExpression()
    * </PRE>
    */
   public void visit(AndOperand n) {
      n.nodeToken.accept(this);
      n.andExpression.accept(this);
   }

   /**
    * <PRE>
    * relationalExpression -> RelationalExpression()
    * nodeOptional -> [ EqualityOperand() ]
    * </PRE>
    */
   public void visit(EqualityExpression n) {
      n.relationalExpression.accept(this);
      n.nodeOptional.accept(this);
   }

   /**
    * <PRE>
    * nodeChoice -> ( &lt;EQ&gt; | &lt;NE&gt; )
    * equalityExpression -> EqualityExpression()
    * </PRE>
    */
   public void visit(EqualityOperand n) {
      n.nodeChoice.accept(this);
      n.equalityExpression.accept(this);
   }

   /**
    * <PRE>
    * shiftExpression -> ShiftExpression()
    * nodeListOptional -> ( RelationalOperand() )*
    * </PRE>
    */
   public void visit(RelationalExpression n) {
      n.shiftExpression.accept(this);
      n.nodeListOptional.accept(this);
   }

   /**
    * <PRE>
    * nodeChoice -> ( &lt;LT&gt; | &lt;LE&gt; | &lt;GT&gt; | &lt;GE&gt; )
    * shiftExpression -> ShiftExpression()
    * </PRE>
    */
   public void visit(RelationalOperand n) {
      n.nodeChoice.accept(this);
      n.shiftExpression.accept(this);
   }

   /**
    * <PRE>
    * additiveExpression -> AdditiveExpression()
    * nodeListOptional -> ( ShiftOperand() )*
    * </PRE>
    */
   public void visit(ShiftExpression n) {
      n.additiveExpression.accept(this);
      n.nodeListOptional.accept(this);
   }

   /**
    * <PRE>
    * nodeChoice -> ( &lt;SHIFTLEFT&gt; | &lt;SHIFTRIGHT&gt; )
    * additiveExpression -> AdditiveExpression()
    * </PRE>
    */
   public void visit(ShiftOperand n) {
      n.nodeChoice.accept(this);
      n.additiveExpression.accept(this);
   }

   /**
    * <PRE>
    * multiplicativeExpression -> MultiplicativeExpression()
    * nodeListOptional -> ( Summand() )*
    * </PRE>
    */
   public void visit(AdditiveExpression n) {
      n.multiplicativeExpression.accept(this);
      n.nodeListOptional.accept(this);
   }

   /**
    * <PRE>
    * nodeChoice -> ( &lt;PLUS&gt; | &lt;MINUS&gt; )
    * multiplicativeExpression -> MultiplicativeExpression()
    * </PRE>
    */
   public void visit(Summand n) {
      n.nodeChoice.accept(this);
      n.multiplicativeExpression.accept(this);
   }

   /**
    * <PRE>
    * castExpression -> CastExpression()
    * nodeListOptional -> ( Multiplicand() )*
    * </PRE>
    */
   public void visit(MultiplicativeExpression n) {
      n.castExpression.accept(this);
      n.nodeListOptional.accept(this);
   }

   /**
    * <PRE>
    * nodeChoice -> ( &lt;MULTIPLY&gt; | &lt;DIVIDE&gt; | &lt;MODULO&gt; )
    * castExpression -> CastExpression()
    * </PRE>
    */
   public void visit(Multiplicand n) {
      n.nodeChoice.accept(this);
      n.castExpression.accept(this);
   }

   /**
    * <PRE>
    * nodeChoice -> CastOperand()
    *       | UnaryExpression()
    * </PRE>
    */
   public void visit(CastExpression n) {
      n.nodeChoice.accept(this);
   }

   /**
    * <PRE>
    * nodeToken -> "("
    * definedType -> DefinedType()
    * nodeToken1 -> ")"
    * castExpression -> CastExpression()
    * </PRE>
    */
   public void visit(CastOperand n) {
      n.nodeToken.accept(this);
      n.definedType.accept(this);
      n.nodeToken1.accept(this);
      n.castExpression.accept(this);
   }

   /**
    * <PRE>
    * nodeChoice -> PostfixExpression()
    *       | UnaryOperand()
    *       | SizeOfOperand()
    * </PRE>
    */
   public void visit(UnaryExpression n) {
      n.nodeChoice.accept(this);
   }

   /**
    * <PRE>
    * nodeChoice -> ( &lt;PLUS&gt; | &lt;MINUS&gt; | &lt;TILDE&gt; | &lt;BANG&gt; )
    * castExpression -> CastExpression()
    * </PRE>
    */
   public void visit(UnaryOperand n) {
      n.nodeChoice.accept(this);
      n.castExpression.accept(this);
   }

   /**
    * <PRE>
    * nodeToken -> &lt;SIZEOF&gt;
    * unaryExpression -> UnaryExpression()
    * </PRE>
    */
   public void visit(SizeOfOperand n) {
      n.nodeToken.accept(this);
      n.unaryExpression.accept(this);
   }

   /**
    * <PRE>
    * primaryExpression -> PrimaryExpression()
    * nodeListOptional -> ( ArrayOperand() | FunctionArgumentList() | DotOperand() | ChoiceOperand() )*
    * </PRE>
    */
   public void visit(PostfixExpression n) {
      n.primaryExpression.accept(this);
      n.nodeListOptional.accept(this);
   }

   /**
    * <PRE>
    * nodeToken -> &lt;IS&gt;
    * nodeToken1 -> &lt;IDENTIFIER&gt;
    * </PRE>
    */
   public void visit(ChoiceOperand n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
   }

   /**
    * <PRE>
    * nodeToken -> "["
    * expression -> Expression()
    * nodeToken1 -> "]"
    * </PRE>
    */
   public void visit(ArrayOperand n) {
      n.nodeToken.accept(this);
      n.expression.accept(this);
      n.nodeToken1.accept(this);
   }

   /**
    * <PRE>
    * nodeToken -> "("
    * nodeOptional -> [ FunctionArgument() ( "," FunctionArgument() )* ]
    * nodeToken1 -> ")"
    * </PRE>
    */
   public void visit(FunctionArgumentList n) {
      n.nodeToken.accept(this);
      n.nodeOptional.accept(this);
      n.nodeToken1.accept(this);
   }

   /**
    * <PRE>
    * nodeToken -> "."
    * nodeToken1 -> &lt;IDENTIFIER&gt;
    * </PRE>
    */
   public void visit(DotOperand n) {
      n.nodeToken.accept(this);
      n.nodeToken1.accept(this);
   }

   /**
    * <PRE>
    * nodeChoice -> VariableName()
    *       | Constant()
    *       | ParenthesizedExpression()
    * </PRE>
    */
   public void visit(PrimaryExpression n) {
      n.nodeChoice.accept(this);
   }

   /**
    * <PRE>
    * nodeToken -> "("
    * expression -> Expression()
    * nodeToken1 -> ")"
    * </PRE>
    */
   public void visit(ParenthesizedExpression n) {
      n.nodeToken.accept(this);
      n.expression.accept(this);
      n.nodeToken1.accept(this);
   }

   /**
    * <PRE>
    * nodeToken -> &lt;IDENTIFIER&gt;
    * </PRE>
    */
   public void visit(VariableName n) {
      n.nodeToken.accept(this);
   }

   /**
    * <PRE>
    * assignmentExpression -> AssignmentExpression()
    * </PRE>
    */
   public void visit(FunctionArgument n) {
      n.assignmentExpression.accept(this);
   }

   /**
    * <PRE>
    * nodeChoice -> &lt;INTEGER_LITERAL&gt;
    *       | &lt;FLOATING_POINT_LITERAL&gt;
    *       | &lt;CHARACTER_LITERAL&gt;
    *       | &lt;STRING_LITERAL&gt;
    * </PRE>
    */
   public void visit(Constant n) {
      n.nodeChoice.accept(this);
   }

}
