//
// Generated by JTB 1.2.2
//

package datascript.visitor;
import datascript.syntaxtree.*;
import java.util.*;

/**
 * All void visitors must implement this interface.
 */
public interface Visitor {
   //
   // void Auto class visitors
   //
   public void visit(NodeList n);
   public void visit(NodeListOptional n);
   public void visit(NodeOptional n);
   public void visit(NodeSequence n);
   public void visit(NodeToken n);

   //
   // User-generated visitor methods below
   //

   /**
    * <PRE>
    * declarationList -> DeclarationList()
    * </PRE>
    */
   public void visit(TranslationUnit n);

   /**
    * <PRE>
    * nodeListOptional -> ( Declaration() )*
    * </PRE>
    */
   public void visit(DeclarationList n);

   /**
    * <PRE>
    * nodeChoice -> FieldDefinition() ";"
    *       | ConditionDefinition()
    *       | ConstDeclaration() ";"
    *       | SqlFieldDefinition() ";"
    * </PRE>
    */
   public void visit(Declaration n);

   /**
    * <PRE>
    * nodeOptional -> [ GlobalLabel() ]
    * expression -> Expression()
    * nodeToken -> ":"
    * </PRE>
    */
   public void visit(Label n);

   /**
    * <PRE>
    * expression -> Expression()
    * nodeToken -> "::"
    * </PRE>
    */
   public void visit(GlobalLabel n);

   /**
    * <PRE>
    * nodeToken -> &lt;CONDITION&gt;
    * nodeToken1 -> &lt;IDENTIFIER&gt;
    * nodeToken2 -> "("
    * nodeOptional -> [ ParameterDefinition() ( "," ParameterDefinition() )* ]
    * nodeToken3 -> ")"
    * nodeToken4 -> "{"
    * nodeListOptional -> ( ConditionExpression() ";" )*
    * nodeToken5 -> "}"
    * </PRE>
    */
   public void visit(ConditionDefinition n);

   /**
    * <PRE>
    * typeDeclaration -> TypeDeclaration()
    * nodeToken -> &lt;IDENTIFIER&gt;
    * </PRE>
    */
   public void visit(ParameterDefinition n);

   /**
    * <PRE>
    * expression -> Expression()
    * </PRE>
    */
   public void visit(ConditionExpression n);

   /**
    * <PRE>
    * nodeChoice -> ( &lt;ENUM&gt; | &lt;BITMASK&gt; )
    * builtinType -> BuiltinType()
    * nodeOptional -> [ &lt;IDENTIFIER&gt; ]
    * nodeToken -> "{"
    * enumItem -> EnumItem()
    * nodeListOptional -> ( "," EnumItem() )*
    * nodeToken1 -> "}"
    * </PRE>
    */
   public void visit(EnumDeclaration n);

   /**
    * <PRE>
    * nodeToken -> &lt;IDENTIFIER&gt;
    * nodeOptional -> [ "=" ConstantExpression() ]
    * </PRE>
    */
   public void visit(EnumItem n);

   /**
    * <PRE>
    * nodeToken -> &lt;CONST&gt;
    * typeDeclaration -> TypeDeclaration()
    * nodeToken1 -> &lt;IDENTIFIER&gt;
    * nodeToken2 -> "="
    * typeValue -> TypeValue()
    * </PRE>
    */
   public void visit(ConstDeclaration n);

   /**
    * <PRE>
    * nodeChoice -> ConstantExpression()
    *       | "{" TypeValueList() "}"
    * </PRE>
    */
   public void visit(TypeValue n);

   /**
    * <PRE>
    * typeValue -> TypeValue()
    * nodeListOptional -> ( "," TypeValue() )*
    * </PRE>
    */
   public void visit(TypeValueList n);

   /**
    * <PRE>
    * sqlType -> SqlType()
    * nodeOptional -> [ &lt;IDENTIFIER&gt; ]
    * nodeSequence -> ( SqlFieldContent() )
    * nodeListOptional -> ( &lt;STRING&gt; )*
    * </PRE>
    */
   public void visit(SqlFieldDefinition n);

   /**
    * <PRE>
    * sqlSyntax -> SqlSyntax()
    * nodeListOptional -> ( "," SqlSyntax() )*
    * </PRE>
    */
   public void visit(SqlFieldContent n);

   /**
    * <PRE>
    * nodeChoice -> &lt;INDEX&gt;
    *       | &lt;CONSTRAINT&gt;
    * </PRE>
    */
   public void visit(SqlType n);

   /**
    * <PRE>
    * nodeOptional -> [ Label() ]
    * typeDeclaration -> TypeDeclaration()
    * nodeOptional1 -> [ TypeArgumentList() ]
    * nodeOptional2 -> [ &lt;IDENTIFIER&gt; ]
    * nodeListOptional -> ( ArrayRange() )*
    * nodeOptional3 -> [ FieldInitializer() ]
    * nodeOptional4 -> [ FieldCondition() ]
    * nodeOptional5 -> [ SqlCondition() ]
    * nodeOptional6 -> [ FieldOptionalClause() ]
    * nodeListOptional1 -> ( &lt;STRING&gt; )*
    * </PRE>
    */
   public void visit(FieldDefinition n);

   /**
    * <PRE>
    * nodeToken -> "("
    * nodeOptional -> [ FunctionArgument() ( "," FunctionArgument() )* ]
    * nodeToken1 -> ")"
    * </PRE>
    */
   public void visit(TypeArgumentList n);

   /**
    * <PRE>
    * nodeToken -> "="
    * typeValue -> TypeValue()
    * </PRE>
    */
   public void visit(FieldInitializer n);

   /**
    * <PRE>
    * nodeToken -> &lt;IF&gt;
    * expression -> Expression()
    * </PRE>
    */
   public void visit(FieldOptionalClause n);

   /**
    * <PRE>
    * nodeToken -> ":"
    * expression -> Expression()
    * </PRE>
    */
   public void visit(FieldCondition n);

   /**
    * <PRE>
    * nodeToken -> &lt;SQL&gt;
    * sqlSyntax -> SqlSyntax()
    * nodeListOptional -> ( "," SqlSyntax() )*
    * </PRE>
    */
   public void visit(SqlCondition n);

   /**
    * <PRE>
    * nodeToken -> &lt;STRING_LITERAL&gt;
    * </PRE>
    */
   public void visit(SqlSyntax n);

   /**
    * <PRE>
    * nodeChoice -> StructDeclaration()
    *       | DefinedType()
    *       | EnumDeclaration()
    * </PRE>
    */
   public void visit(TypeDeclaration n);

   /**
    * <PRE>
    * nodeOptional -> [ ByteOrderModifier() ]
    * nodeOptional1 -> [ &lt;UNION&gt; | &lt;DATABASE&gt; | &lt;TABLE&gt; | &lt;SQLINTEGER&gt; | &lt;SQLTEXT&gt; ]
    * nodeOptional2 -> [ &lt;IDENTIFIER&gt; ]
    * nodeOptional3 -> [ "(" ParameterDefinition() ( "," ParameterDefinition() )* ")" ]
    * nodeToken -> "{"
    * declarationList -> DeclarationList()
    * nodeToken1 -> "}"
    * </PRE>
    */
   public void visit(StructDeclaration n);

   /**
    * <PRE>
    * nodeChoice -> TypeSymbol()
    *       | BuiltinType()
    * </PRE>
    */
   public void visit(DefinedType n);

   /**
    * <PRE>
    * nodeToken -> &lt;IDENTIFIER&gt;
    * nodeListOptional -> ( DotOperand() )*
    * </PRE>
    */
   public void visit(TypeSymbol n);

   /**
    * <PRE>
    * nodeOptional -> [ ByteOrderModifier() ]
    * nodeChoice -> ( &lt;UINT8&gt; | &lt;UINT16&gt; | &lt;UINT32&gt; | &lt;UINT64&gt; | &lt;INT8&gt; | &lt;INT16&gt; | &lt;INT32&gt; | &lt;INT64&gt; | &lt;STRING&gt; | BitField() )
    * </PRE>
    */
   public void visit(BuiltinType n);

   /**
    * <PRE>
    * nodeToken -> &lt;BIT&gt;
    * nodeChoice -> ( ":" &lt;INTEGER_LITERAL&gt; | &lt;LT&gt; ShiftExpression() &lt;GT&gt; )
    * </PRE>
    */
   public void visit(BitField n);

   /**
    * <PRE>
    * nodeChoice -> &lt;BIG&gt;
    *       | &lt;LITTLE&gt;
    * </PRE>
    */
   public void visit(ByteOrderModifier n);

   /**
    * <PRE>
    * nodeToken -> "["
    * nodeOptional -> [ RangeExpression() ]
    * nodeToken1 -> "]"
    * </PRE>
    */
   public void visit(ArrayRange n);

   /**
    * <PRE>
    * assignmentExpression -> AssignmentExpression()
    * nodeListOptional -> ( CommaOperand() )*
    * </PRE>
    */
   public void visit(Expression n);

   /**
    * <PRE>
    * nodeToken -> ","
    * assignmentExpression -> AssignmentExpression()
    * </PRE>
    */
   public void visit(CommaOperand n);

   /**
    * <PRE>
    * nodeChoice -> UnaryExpression() AssignmentOperator() AssignmentExpression()
    *       | QuantifiedExpression()
    * </PRE>
    */
   public void visit(AssignmentExpression n);

   /**
    * <PRE>
    * nodeChoice -> ( "=" | "*=" | "/=" | "%=" | "+=" | "-=" | "&lt;&lt;=" | "&gt;&gt;=" | "&=" | "^=" | "|=" )
    * </PRE>
    */
   public void visit(AssignmentOperator n);

   /**
    * <PRE>
    * nodeOptional -> [ Quantifier() ]
    * conditionalExpression -> ConditionalExpression()
    * </PRE>
    */
   public void visit(QuantifiedExpression n);

   /**
    * <PRE>
    * nodeToken -> &lt;FORALL&gt;
    * nodeToken1 -> &lt;IDENTIFIER&gt;
    * nodeToken2 -> &lt;IN&gt;
    * unaryExpression -> UnaryExpression()
    * nodeToken3 -> ":"
    * </PRE>
    */
   public void visit(Quantifier n);

   /**
    * <PRE>
    * logicalOrExpression -> LogicalOrExpression()
    * nodeOptional -> [ ConditionalExpressionOperand() ]
    * </PRE>
    */
   public void visit(ConditionalExpression n);

   /**
    * <PRE>
    * nodeToken -> &lt;QUESTIONMARK&gt;
    * expression -> Expression()
    * nodeToken1 -> ":"
    * conditionalExpression -> ConditionalExpression()
    * </PRE>
    */
   public void visit(ConditionalExpressionOperand n);

   /**
    * <PRE>
    * conditionalExpression -> ConditionalExpression()
    * </PRE>
    */
   public void visit(ConstantExpression n);

   /**
    * <PRE>
    * expression -> Expression()
    * nodeOptional -> [ UpperBoundExpression() ]
    * </PRE>
    */
   public void visit(RangeExpression n);

   /**
    * <PRE>
    * nodeToken -> &lt;RANGE&gt;
    * expression -> Expression()
    * </PRE>
    */
   public void visit(UpperBoundExpression n);

   /**
    * <PRE>
    * logicalAndExpression -> LogicalAndExpression()
    * nodeOptional -> [ LogicalOrOperand() ]
    * </PRE>
    */
   public void visit(LogicalOrExpression n);

   /**
    * <PRE>
    * nodeToken -> &lt;LOGICALOR&gt;
    * logicalOrExpression -> LogicalOrExpression()
    * </PRE>
    */
   public void visit(LogicalOrOperand n);

   /**
    * <PRE>
    * inclusiveOrExpression -> InclusiveOrExpression()
    * nodeOptional -> [ LogicalAndOperand() ]
    * </PRE>
    */
   public void visit(LogicalAndExpression n);

   /**
    * <PRE>
    * nodeToken -> &lt;LOGICALAND&gt;
    * logicalAndExpression -> LogicalAndExpression()
    * </PRE>
    */
   public void visit(LogicalAndOperand n);

   /**
    * <PRE>
    * exclusiveOrExpression -> ExclusiveOrExpression()
    * nodeOptional -> [ InclusiveOrOperand() ]
    * </PRE>
    */
   public void visit(InclusiveOrExpression n);

   /**
    * <PRE>
    * nodeToken -> &lt;OR&gt;
    * inclusiveOrExpression -> InclusiveOrExpression()
    * </PRE>
    */
   public void visit(InclusiveOrOperand n);

   /**
    * <PRE>
    * andExpression -> AndExpression()
    * nodeOptional -> [ ExclusiveOrOperand() ]
    * </PRE>
    */
   public void visit(ExclusiveOrExpression n);

   /**
    * <PRE>
    * nodeToken -> &lt;XOR&gt;
    * exclusiveOrExpression -> ExclusiveOrExpression()
    * </PRE>
    */
   public void visit(ExclusiveOrOperand n);

   /**
    * <PRE>
    * equalityExpression -> EqualityExpression()
    * nodeOptional -> [ AndOperand() ]
    * </PRE>
    */
   public void visit(AndExpression n);

   /**
    * <PRE>
    * nodeToken -> &lt;AND&gt;
    * andExpression -> AndExpression()
    * </PRE>
    */
   public void visit(AndOperand n);

   /**
    * <PRE>
    * relationalExpression -> RelationalExpression()
    * nodeOptional -> [ EqualityOperand() ]
    * </PRE>
    */
   public void visit(EqualityExpression n);

   /**
    * <PRE>
    * nodeChoice -> ( &lt;EQ&gt; | &lt;NE&gt; )
    * equalityExpression -> EqualityExpression()
    * </PRE>
    */
   public void visit(EqualityOperand n);

   /**
    * <PRE>
    * shiftExpression -> ShiftExpression()
    * nodeListOptional -> ( RelationalOperand() )*
    * </PRE>
    */
   public void visit(RelationalExpression n);

   /**
    * <PRE>
    * nodeChoice -> ( &lt;LT&gt; | &lt;LE&gt; | &lt;GT&gt; | &lt;GE&gt; )
    * shiftExpression -> ShiftExpression()
    * </PRE>
    */
   public void visit(RelationalOperand n);

   /**
    * <PRE>
    * additiveExpression -> AdditiveExpression()
    * nodeListOptional -> ( ShiftOperand() )*
    * </PRE>
    */
   public void visit(ShiftExpression n);

   /**
    * <PRE>
    * nodeChoice -> ( &lt;SHIFTLEFT&gt; | &lt;SHIFTRIGHT&gt; )
    * additiveExpression -> AdditiveExpression()
    * </PRE>
    */
   public void visit(ShiftOperand n);

   /**
    * <PRE>
    * multiplicativeExpression -> MultiplicativeExpression()
    * nodeListOptional -> ( Summand() )*
    * </PRE>
    */
   public void visit(AdditiveExpression n);

   /**
    * <PRE>
    * nodeChoice -> ( &lt;PLUS&gt; | &lt;MINUS&gt; )
    * multiplicativeExpression -> MultiplicativeExpression()
    * </PRE>
    */
   public void visit(Summand n);

   /**
    * <PRE>
    * castExpression -> CastExpression()
    * nodeListOptional -> ( Multiplicand() )*
    * </PRE>
    */
   public void visit(MultiplicativeExpression n);

   /**
    * <PRE>
    * nodeChoice -> ( &lt;MULTIPLY&gt; | &lt;DIVIDE&gt; | &lt;MODULO&gt; )
    * castExpression -> CastExpression()
    * </PRE>
    */
   public void visit(Multiplicand n);

   /**
    * <PRE>
    * nodeChoice -> CastOperand()
    *       | UnaryExpression()
    * </PRE>
    */
   public void visit(CastExpression n);

   /**
    * <PRE>
    * nodeToken -> "("
    * definedType -> DefinedType()
    * nodeToken1 -> ")"
    * castExpression -> CastExpression()
    * </PRE>
    */
   public void visit(CastOperand n);

   /**
    * <PRE>
    * nodeChoice -> PostfixExpression()
    *       | UnaryOperand()
    *       | SizeOfOperand()
    * </PRE>
    */
   public void visit(UnaryExpression n);

   /**
    * <PRE>
    * nodeChoice -> ( &lt;PLUS&gt; | &lt;MINUS&gt; | &lt;TILDE&gt; | &lt;BANG&gt; )
    * castExpression -> CastExpression()
    * </PRE>
    */
   public void visit(UnaryOperand n);

   /**
    * <PRE>
    * nodeToken -> &lt;SIZEOF&gt;
    * unaryExpression -> UnaryExpression()
    * </PRE>
    */
   public void visit(SizeOfOperand n);

   /**
    * <PRE>
    * primaryExpression -> PrimaryExpression()
    * nodeListOptional -> ( ArrayOperand() | FunctionArgumentList() | DotOperand() | ChoiceOperand() )*
    * </PRE>
    */
   public void visit(PostfixExpression n);

   /**
    * <PRE>
    * nodeToken -> &lt;IS&gt;
    * nodeToken1 -> &lt;IDENTIFIER&gt;
    * </PRE>
    */
   public void visit(ChoiceOperand n);

   /**
    * <PRE>
    * nodeToken -> "["
    * expression -> Expression()
    * nodeToken1 -> "]"
    * </PRE>
    */
   public void visit(ArrayOperand n);

   /**
    * <PRE>
    * nodeToken -> "("
    * nodeOptional -> [ FunctionArgument() ( "," FunctionArgument() )* ]
    * nodeToken1 -> ")"
    * </PRE>
    */
   public void visit(FunctionArgumentList n);

   /**
    * <PRE>
    * nodeToken -> "."
    * nodeToken1 -> &lt;IDENTIFIER&gt;
    * </PRE>
    */
   public void visit(DotOperand n);

   /**
    * <PRE>
    * nodeChoice -> VariableName()
    *       | Constant()
    *       | ParenthesizedExpression()
    * </PRE>
    */
   public void visit(PrimaryExpression n);

   /**
    * <PRE>
    * nodeToken -> "("
    * expression -> Expression()
    * nodeToken1 -> ")"
    * </PRE>
    */
   public void visit(ParenthesizedExpression n);

   /**
    * <PRE>
    * nodeToken -> &lt;IDENTIFIER&gt;
    * </PRE>
    */
   public void visit(VariableName n);

   /**
    * <PRE>
    * assignmentExpression -> AssignmentExpression()
    * </PRE>
    */
   public void visit(FunctionArgument n);

   /**
    * <PRE>
    * nodeChoice -> &lt;INTEGER_LITERAL&gt;
    *       | &lt;FLOATING_POINT_LITERAL&gt;
    *       | &lt;CHARACTER_LITERAL&gt;
    *       | &lt;STRING_LITERAL&gt;
    * </PRE>
    */
   public void visit(Constant n);

}

